import configparser

# Define path for settings.ini file here.
SETTINGS_FILE = '/Users/tim/PycharmProjects/DSA/Sorts/settings.ini'

config = configparser.ConfigParser()
config.sections()
config.read(SETTINGS_FILE)

# Define paths to your test cases in the settings.ini file and then add the new values below
SORT_TEST_CASES = config['SORTING TEST CASES']['SORT_TESTCASES']

INSERTION_SORT_TESTCASES = config['INSERTION SORT TESTCASES']['INSERTION_SORT_TESTCASES']
INSERTION_SORT_RESULTS = config['INSERTION SORT TESTCASES']['INSERTION_SORT_RESULTS']
EXPECTED_INSERTION_SORT_RESULTS = config['INSERTION SORT TESTCASES']['EXPECTED_INSERTION_SORT_RESULTS']

SELECTION_SORT_TESTCASES = config['SELECTION SORT TESTCASES']['SELECTION_SORT_TESTCASES']
SELECTION_SORT_RESULTS = config['SELECTION SORT TESTCASES']['SELECTION_SORT_RESULTS']
EXPECTED_SELECTION_SORT_RESULTS = config['SELECTION SORT TESTCASES']['EXPECTED_SELECTION_SORT_RESULTS']

MERGE_SORT_TESTCASES = config['MERGE SORT TESTCASES']['MERGE_SORT_TESTCASES']
MERGE_SORT_RESULTS = config['MERGE SORT TESTCASES']['MERGE_SORT_RESULTS']
EXPECTED_MERGE_SORT_RESULTS = config['MERGE SORT TESTCASES']['EXPECTED_MERGE_SORT_RESULTS']
